version: '3.8'

services:
  nodejs-app:
    image: node:latest
    container_name: nestjs-container
    build: 
      context: .
    env_file:
      - .development.env
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4040:4040"
    environment:
      - NODE_ENV=development
    command: npm run start
    depends_on:
      - postgres-db 
    restart: always

  postgres-db:
    image: postgres:latest 
    container_name: postgres-container
    env_file:
      - .development.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecretKey
      POSTGRES_DB: db_notes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    restart: always
volumes:
  postgres-data:
